# Generated by Django 5.2 on 2025-04-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("blik", "BLIK"), ("cash", "Cash"), ("card", "Card")],
                default="cash",
                max_length=30,
            ),
        ),
    ]
