# Generated by Django 5.2 on 2025-04-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="mechanic",
        ),
    ]
